blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/DiogoRibeiro7/rcpsp_cf_ivfth/security/advisories/new
    about: Please report security vulnerabilities using GitHub Security Advisories.
